[project]
name = "dynatask"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = ["valkey == 6.2.0rc1"]

[project.urls]
Homepage = "https://github.com/ludo-lumapps/dynatask-py"

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project.optional-dependencies]
test = ["pytest", "msgspec"]
